#!/usr/bin/env bash
# Real-terminal Ducklord create E2E. The fixture is credential-free and drives
# TUI input through a PTY into the SSH stdio bridge and a native Ducklion PTY.
# Fixture containers and its network use DUCKLORD_TUI_E2E_NAME_PREFIX (a
# process-unique prefix by default).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/scripts/container-runtime.sh"
source "$ROOT/scripts/ducklord-demo-common.sh"
duckway_init_container_runtime
RUNTIME="$CONTAINER_RUNTIME"
NAME_PREFIX="${DUCKLORD_TUI_E2E_NAME_PREFIX:-ducklord-tui-e2e-${BASHPID}}"
case "$NAME_PREFIX" in
  *[!A-Za-z0-9_.-]*) echo "invalid DUCKLORD_TUI_E2E_NAME_PREFIX=$NAME_PREFIX" >&2; exit 2 ;;
esac
DEV_CONTAINER="${NAME_PREFIX}-ducklord-dev"
CLIENT_A="${NAME_PREFIX}-ducklion-client-a"
CLIENT_B="${NAME_PREFIX}-ducklion-client-b"
CLIENT_C="${NAME_PREFIX}-ducklion-client-c"
CLIENT_D="${NAME_PREFIX}-ducklion-client-d"
NET="${DUCKLORD_TUI_E2E_NETWORK:-${NAME_PREFIX}-ducklord-demo}"
if [ "${DUCKLORD_TUI_E2E_OWNER_TOKEN+x}" = x ]; then
	echo "DUCKLORD_TUI_E2E_OWNER_TOKEN is generated by the isolated E2E and cannot be set" >&2
	exit 2
fi
# The token must be per-process and unpredictable enough that a stale resource
# or concurrent run cannot be mistaken for this run's network.
OWNER_TOKEN="${NAME_PREFIX}-${BASHPID}-$(date +%s%N)-${RANDOM}"
SETUP_LOG="$(mktemp -t ducklord-tui-e2e-XXXXXX.log)"
if [ "${DUCKLORD_DEMO_LOCK_HELD:-0}" != 1 ]; then
	rm -f "$SETUP_LOG"
	ducklord_reexec_with_demo_lock "$0" "$@"
fi

for resource in "$DEV_CONTAINER" "$CLIENT_A" "$CLIENT_B" "$CLIENT_C" "$CLIENT_D"; do
	if "$RUNTIME" container inspect "$resource" >/dev/null 2>&1; then
		echo "[ducklord-tui-e2e] refusing to replace existing container $resource" >&2
		rm -f "$SETUP_LOG"
		exit 1
	fi
done
if "$RUNTIME" network inspect "$NET" >/dev/null 2>&1; then
	echo "[ducklord-tui-e2e] refusing to replace existing network $NET" >&2
	rm -f "$SETUP_LOG"
	exit 1
fi

cleanup() {
	local status=$?
	trap - EXIT INT TERM
  for resource in "$DEV_CONTAINER" "$CLIENT_A" "$CLIENT_B" "$CLIENT_C" "$CLIENT_D"; do
    if [ "$("$RUNTIME" container inspect -f '{{ index .Config.Labels "ducklord.demo.owner" }}' "$resource" 2>/dev/null || true)" = "$OWNER_TOKEN" ]; then
      "$RUNTIME" rm -f "$resource" >/dev/null 2>&1 || true
    fi
  done
  if [ "$("$RUNTIME" network inspect -f '{{ index .Labels "ducklord.demo.owner" }}' "$NET" 2>/dev/null || true)" = "$OWNER_TOKEN" ]; then
    "$RUNTIME" network rm "$NET" >/dev/null 2>&1 || true
  fi
	if [ "$status" -ne 0 ]; then
		echo "[ducklord-tui-e2e] setup tail:" >&2
		tail -n 40 "$SETUP_LOG" >&2 || true
	fi
	rm -f "$SETUP_LOG"
	exit "$status"
}
trap cleanup EXIT INT TERM

echo "[ducklord-tui-e2e] preparing credential-free Ducklion topology with $RUNTIME"
DUCKLORD_DEMO_LOCK_HELD=1 DUCKLORD_DEMO_NAME_PREFIX="$NAME_PREFIX" NET="$NET" DUCKLORD_DEMO_OWNER_TOKEN="$OWNER_TOKEN" DUCKLORD_DEMO_AGENT_CREDENTIALS=none DUCKLORD_DEMO_SHELL_ONLY=1 DUCKLORD_DEMO_INCLUDE_CLIENT_C=0 DUCKLORD_DEMO_INCLUDE_CLIENT_D=0 \
CONTAINER_RUNTIME="$RUNTIME" "$ROOT/scripts/ducklord-podman-demo.sh" --require-owned-network >"$SETUP_LOG"
"$RUNTIME" exec "$DEV_CONTAINER" sh -lc "sed 's/^name: .*/name: e2e-inspector/' /root/.ducklord/config.yaml >/tmp/e2e-inspector.yaml"

echo "[ducklord-tui-e2e] driving create modal, SSH bridge, and remote PTY"
# TestDucklordOutputSearchBookmarksContainerE2E
DEFAULT_PATTERN='^TestDucklord(OutputSearchBookmarksContainer|CommandPaletteContainer|CreateTUIContainer|WorkspacePreviewContainer|WorkspaceDefaultNewShellSplitContainer|FocusedPrefixQuickShell(Horizontal|Vertical|Tab)Container|WorkspaceTwoLivePanesContainer|WorkspaceProjectEnterFocusContainer|SharedProjectNotificationContainer|DetailedListContainer|DetailedUnreadFilterContainer|DetailedOfflineContainer|HostRetentionContainer|HostHookConfigContainer|LocalNotificationContainer|ShellFirstHookContainer|ProjectDeleteContainer|ProjectTransferContainer|ForegroundAgentLabelsContainer|ShellRetirementContainer|ExplicitShellEndRetainsLogContainer|ShellEndModalContainer|DefaultDetachContainer|PaneControlContractContainer|PrefixNavigationContainer|MixedHostProjectContainer|NotesTUIContainer|HostSkillsContainer|HostResourcesContainer'
DEFAULT_PATTERN+='|FileExchangeContainer)E2E$'
# Exact route-manifest names covered by the regex above. Keep this list aligned
# with docs/ui-routing-verification.md; check-routing-manifest.sh verifies it.
# TestDucklordPrefixNavigationContainerE2E
# TestDucklordDetailedListContainerE2E
# TestDucklordWorkspaceProjectEnterFocusContainerE2E
# TestDucklordPaneControlContractContainerE2E
# TestDucklordNotesTUIContainerE2E
# TestDucklordHostSkillsContainerE2E
# TestDucklordHostResourcesContainerE2E
# TestDucklordProjectTransferContainerE2E
# TestDucklordCreateTUIContainerE2E
# TestDucklordFocusedPrefixQuickShellHorizontalContainerE2E
# TestDucklordFocusedPrefixQuickShellVerticalContainerE2E
# TestDucklordFocusedPrefixQuickShellTabContainerE2E
# TestDucklordFileExchangeContainerE2E
PATTERN="${DUCKLORD_TUI_E2E_PATTERN:-$DEFAULT_PATTERN}"
DUCKLORD_TUI_CONTAINER_E2E=1 \
DUCKLORD_E2E_DISPOSABLE_HOST=1 \
DUCKLORD_E2E_RUNTIME="$RUNTIME" \
DUCKLORD_E2E_CONTAINER_PREFIX="$NAME_PREFIX" \
DUCKLORD_E2E_CONTROLLER="$DEV_CONTAINER" \
DUCKLORD_E2E_OWNER_TOKEN="$OWNER_TOKEN" \
DUCKLORD_NOTES_TUI_E2E=1 \
go test -count=1 ./cmd/ducklord -run "$PATTERN" -v

echo "[ducklord-tui-e2e] PASS"
